---
- name: Ensure Redis is installed.
  apt:
    name: "{{ redis_package }}"
    state: present
  when:
    - not redis_install_from_source | bool

- name: Install Redis from source.
  include_tasks: install-from-source.yml
  when: redis_install_from_source | bool
